name: Test CI
on:
  push:
    branches: [ main ]
  workflow_dispatch: # 新增这一行，开启手动触发
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: echo "CI run ok"
